name: Build All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2019-q4'
    - name: Build Libraries
      run: ./ci/build_libs.sh
    - name: Build Examples
      run: ./ci/build_examples.sh
