name: Run Style Fix

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: './DaisySP ./libDaisy'
        extensions: 'h,cpp'
        clangFormatVersion: 10
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

